version: 0.2

env:
 exported-variables:
   - IMAGE_TAG
phases:
  install:
    commands:
      - curl -sLO https://github.com/kayac/ecspresso/releases/download/v1.7.11/ecspresso_1.7.11_linux_amd64.tar.gz
      - tar -C /usr/local/bin -zxf ecspresso_1.7.11_linux_amd64.tar.gz ecspresso
      - git clone https://github.com/tfutils/tfenv.git ~/.tfenv
      - ln -s ~/.tfenv/bin/* /usr/local/bin
  pre_build:
    commands:
      - tfenv install
      - cd terraform
      - ls -a
      - cd ..
  build:
    commands:
      - cd ecspresso
      - ls -a
  post_build:
    commands:
      - echo Build completed on `date`
      - IMAGE_TAG=foobar.`date`
      - export IMAGE_TAG

