name: github discussions reusable workflow

on:
  workflow_call:
    inputs:
      channel_id:
        required: true
        type: string

jobs:
  discussion_commented:
    runs-on: ubuntu-20.04
    if: github.event.comment
    steps:
      - name: Send GitHub Discussions Comments to Slack
        run: |
          echo ${{ toJSON(github.event) }}
