name: Detect changed files

on:
  workflow_call:
    inputs:
      pattern:
        description: Pattern to match changed files
        required: true
        type: string
    outputs:
      changed-files:
        description: Changed files
        value: ${{ jobs.changed-files.outputs.changed-files }}

jobs:
  changed-files:
    runs-on: ubuntu-latest
    outputs:
      changed-files: ${{ steps.changed-files.outputs.changed-files }}

    steps:
      - uses: actions/checkout@v5

      - name: Unshallow git
        run: git fetch --prune --unshallow

      - name: Get changed files
        id: changed-files
        shell: bash
        run: |
          pattern=${{ inputs.pattern }}
  
          CURRENT_BRANCH="$(git rev-parse --abbrev-ref HEAD)"

          if [[ "$CURRENT_BRANCH" == "master" || "$CURRENT_BRANCH" == "develop" ]]; then
            SOURCE_TARGET="HEAD^"
            DESTINATION_TARGET="HEAD"
          else
            SOURCE_TARGET="origin/${GITHUB_BASE_REF}"
            DESTINATION_TARGET="HEAD"
          fi

          changed_files=$(git diff $SOURCE_TARGET $DESTINATION_TARGET --name-only --no-color | grep -e "$pattern" || :)

          # Remove empty lines and lines start with `./`
          changed_files=$(echo "$changed_files" | grep -v -e '^\s*$' | sed -e 's/^\.\///g' || :)
        
          # Replace return code with space and trim leading/trailing spaces
          changed_files=$(echo $changed_files | tr '\n' ' ' | sed 's/^ *\| *$//')
  
          echo "::set-output name=changed-files::$changed_files"
