name: reusable workflow

on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string

jobs:
  test:
    environment: productio
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    steps:
      - uses: actions/checkout@v3
      - run: echo ${{ toJSON(github.jobs) }} 

