name: changed files

on:
  pull_request:

jobs:
  changed-files:
    uses: ./.github/workflows/_get_changed_files.yaml
    with:
      pattern: .yaml

  test:
    needs: [changed-files]
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ needs.changed-files.outputs.changed-files }}
