name: changed files

on:
  pull_request:

jobs:
  changed-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - id: changed-files
        uses: ./.github/actions/get_changed_files
        with:
          pattern: tfmigrate/

      - run: echo ${{ steps.changed-files.outputs.changed-files }}

      - if: contains(steps.changed-files.outputs.changed-files, 'tfmigrate/')
        run: echo "Contains tfmigrate"

      - if: ! contains(steps.changed-files.outputs.changed-files, 'tfmigrate/')
        run: echo "Not contains tfmigrate"
