name: changed files

on:
  pull_request:

jobs:
  changed-files:
    uses: ./.github/workflows/_get_changed_files.yaml
    with:
      pattern: .sh

  test:
    needs: [changed-files]
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ needs.changed-files.outputs.changed-files }}

      - if: needs.changed-files.outputs.changed-files != ''
        run: echo "YAML files detected"

      - if: needs.changed-files.outputs.changed-files == ''
        run: echo "YAML files not detected"
