name: echo

on:
  pull_request:
    types: [closed]

permissions:
  id-token: write
  contents: read

jobs:
  echo:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - run: echo ${{ toJSON(github.event) }}

