name: echo

on:
  pull_request:

permissions:
  contents: read

jobs:
  echo:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - run: echo ${FOO}
    env:
      FOO: ${{ secrets.FOO }}

