name: echo

on:
  push:
    tags:
      - test

permissions:
  id-token: write
  contents: read

jobs:
  echo:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - run: echo ${SLACK_WEBHOOK_URL}
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

