name: iteration

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        iteration: [1, 2, 3, 4, 5]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run job
      run: echo "Iteration ${{ matrix.iteration }}"

