name: Reusable workflow with matrix strategy

on:
  pull_request:

jobs:
  ReuseableMatrixJobForDeployment:
    strategy:
      matrix:
        target: [dev, stage, prod]
    uses: .github/workflows/_reusable_workflow.yaml
    with:
      wowking-directory: ${{ matrix.target }}
