name: test

on:
  pull_request:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - id: foo
        run: echo foo=bar >> $GITHUB_ENV
    outputs:
      foo: ${{ env.foo }}

  job2:
    needs: [job1]
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ needs.job1.outputs.foo }}
