name: test

on:
  pull_request:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo ::set-output name=foo::bar

  job2:
    needs: [job1]
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ needs.job1.outputs.foo }}
