name: update pr

on:
  push

permissions:
  contents: write
  pull-requests: write

jobs:
  update-pr:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - run: gh help
