name: update pr

on:
  push

permissions:
  contents: read
  pull-requests: write

jobs:
  update-pr:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - run: gh api -X PUT "repos/mizzy/test/pulls/14/update-branch"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
