name: update pr

on:
  push

permissions:
  contents: write
  pull-requests: write

jobs:
  update-pr:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - use: actions/checkout@v3
      - run: gh api -X PUT "repos/{owner}/{repo}/pulls/16/update-branch"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
